### ISSUE TITLE
ChangeLog & Blog Entry Date

### ISSUE THREAD

**Issue by vision8tech** [vert-x3/vertx-guide-for-java-devs#18]
Dear authors,

This material is lovely and I thank you very much for the effort you put into it.

I would consider in future release including a _Change Log_ section.

Besides this, I would update the [vertx.io/materials](http://vertx.io/materials/) entry to reflect the current date of the material.

![image](https://user-images.githubusercontent.com/14140226/31904074-dd429b48-b832-11e7-958e-6da0c7b12189.png)

Thanks.

**Comment by vietj** [comment]
thanks I've updated the date

we don't maintain a change log for the book (perhaps we should consider it as it's a living book)

you can see the changes in the github repo : https://github.com/vert-x3/vertx-guide-for-java-devs/commits/master

Julien

**Comment by vision8tech** [comment]
Hi Julien,

You're right: commits can help!

Thanks for the quick feedback!
