### ISSUE TITLE
Intro feedback

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-guide-for-java-devs#2]
(apart from the typos in PR #1 )

## Reactor / Event-Loop / Verticle instead of introducing Verticle right away ?

Wouldn't it be better to talk about the Event-Loop before talking about Verticles ? (just asking).

In my mind, it's easier to reason about "the mono-reactor pattern", understand that a piece of code (even asynchronous) will run on one thread, then extend to multi-reactor pattern, then attach the concept of a Verticle to the concept of an event-loop. Saying it's a 1 to 1 relation by default, but not mandatory. And that THIS is the major way of scaling the application.

It's a very personnal pov, obviously, but it sounds more natural to me: 

1. A reminder about threading models (some of the "enterprise developers" don't know the traditional threading model in an application server)

2. Introducing the reactor pattern, and the concept of event-loop (Swing's EDT is a good comparison nice to see it, maybe mentioning Android's "main" thread would be interesting ?)

3. Attach the concept of verticle to the event-loop. 

----------------------

## Event-Bus

Maybe the schema HTTP Verticle <=> SQL Verticle could benefit from "workflow" annotations (on the arrows) ?
Like : 

1. Ask for details
2. Fetch SQL data
3. Reply with data over the EB

Because it's not straightforward to understand how the flow works (in time).

> a SockJS bridge allows web applications to seamlessly communicate over the event bus

Maybe mention websockets, server-sent-event, long HTTP polling, for those who don't know about SockJS.

**Comment by jponge** [comment]
Thanks @aesteve!
