### ISSUE TITLE
It seems that markdown has broken

### ISSUE THREAD

**Issue by sleshJdev** [vert-x3/vertx-guide-for-java-devs#21]
Hi, guys, could you please fix the markdown [here](https://github.com/vert-x3/vertx-guide-for-java-devs/blob/master/step-2/README.adoc). For example, this line **link:src/main/java/io/vertx/guides/wiki/HttpServerVerticle.java[]** and there are more ones

**Comment by jponge** [comment]
@sleshJdev It's not Markdown but Asciidoc.

GitHub does not render file includes for obvious security reasons, so when you look at the files from the GitHub UI all you see is links.

You can get the latest published version at http://vertx.io/docs/guide-for-java-devs/
