### ISSUE TITLE
Api Rest Architecture

### ISSUE THREAD

**Issue by milo2005** [vert-x3/vertx-guide-for-java-devs#31]
Hi !
I am developing an Api Rest with many resources, but i dont know how to define the architecture of the application, so i have this questions:

- ¿ Should i make a verticle for each Resource Type?
- ¿ Should i make a Proxy Service for each Resource Type and bind to a single Verticle?
- ¿ The number of Verticles should be the same cores number ? or ¿ The number of the verticles instance should be the same core number?

Thanks for your help :D

**Comment by milo2005** [comment]
In this moment i have this structure:
MainVerticle
http/
         HttpVerticle
login/
         LoginVerticle
         LoginRoutes
         service/
                   LoginService
                   LoginServiceImpl
...
resourceN/
         ResourceNVerticle
         ResourceNRoutes
         service/
                     ResourceNService
                     ResourceNServiceImpl

The MainVertcle deploy the resources verticles, each resource verticle expose the access data to MongoDB  through the proxy service

.The HttpVerticle load each resource route.

I dont know if this structure have a bad performance in the server or for other way, it gives flexibility to decide which resource needs more verticle instances to improve the behavior.

Thanks :D

**Comment by jponge** [comment]
Hi @milo2005 you should contact us on the users mailing-list and/or the Gitter chat channel, see http://vertx.io/community/

Thanks!
