### ISSUE TITLE
Step 5: Anonymous gist creation is deactivated.

### ISSUE THREAD

**Issue by Chessray** [vert-x3/vertx-guide-for-java-devs#34]
GitHub [no longer allows](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/) creating Gists anonymously. I circumvented the issue by creating a personal access token for gists and adding this as authorization header in the backupHandler method:

`.putHeader("Authorization", "token xxxxxxxxxxxxxxxx")`

**Comment by Chessray** [comment]
As mentioned, this is how I circumvented the issue. But do you really wish to promote a solution that basically requires a secret in source code? There must be better ways to tackle this; in the Gitter chat it was suggested to just create a specific access token for a "generic" Vert.x GitHub user and using this.

Just pointing out the concern before I submit a solution that wouldn't be fir for purpose in the end.

**Comment by jponge** [comment]
Very good points.

Secrets shall never be in source code, and creating fake / generic accounts is generally against _terms of service agreements_.

A better option is looking at the Pastebin API instead, what do you think?

**Comment by jponge** [comment]
Ah wrong, you need a key as well https://pastebin.com/api

**Comment by FroMage** [comment]
So it sucks: gists requires oauth now, and I couldn't find any other provider which didn't require auth, so I went ahead and implemented the oauth flow in my wiki example for redpipe, if you want inspiration:

https://github.com/FroMage/redpipe/commit/a2c6f34a8d2ca86e150d0e743ff8146a5a7e364b

Workflow sucks, because I store this token in a session and they're not persisted across restarts, but I couldn't think of better.

**Comment by jponge** [comment]
What if we wrote a simple side service to be shipped with the wiki?

The goal is to show HTTP service integration after all...

**Comment by jponge** [comment]
I may have found a replace service: https://glot.io/

It seems like creating anonymous snippets is possible, and the API is very similar: https://github.com/prasmussen/glot-snippets/blob/master/api_docs/create_snippet.md

Thoughts?

**Comment by jponge** [comment]
<img width="588" alt="screen shot 2018-04-09 at 11 52 33" src="https://user-images.githubusercontent.com/25961/38491577-8952015c-3bec-11e8-83d9-087b71397ce4.png">

Got it working with Glot.io, I'm preparing updates to the text and code.
