### ISSUE TITLE
Upgrade to Bootstrap 4.0.0

### ISSUE THREAD

**Issue by jponge** [vert-x3/vertx-guide-for-java-devs#43]
The guide uses older beta versions.

**Comment by lalitjeevanrao** [comment]
@jponge FTL files like header.ftl contains bootstrap version as 4.0.0-alpha.5
Do you wish to upgrade to 4.0.0 or the latest 4.1.3?

**Comment by jponge** [comment]
Thank you!

**Comment by lalitjeevanrao** [comment]
Pleasure was mine @jponge
