### ISSUE TITLE
Using helpers to generate observables from the SQLClient

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-guide-for-java-devs#47]
In vert-x3/vertx-rx#148 , we are thinking about how to simplify usage of Rxified SQLClient to generate `Observable` and friends.

When it's done, the guide could use the new helpers.

**Comment by tsegismont** [comment]
@jponge where should I contribute this? In a specific branch? Or is master PR fine?

**Comment by jponge** [comment]
Hi Thomas,

Please just make a branch on this repo then create a PR to merge back into master.

Thanks a lot!

**Comment by tsegismont** [comment]
Fixed in #53
