### ISSUE TITLE
Fluent interface in step 3 add no value

### ISSUE THREAD

**Issue by gargoyle** [vert-x3/vertx-guide-for-java-devs#51]
Hi All,

I have 20 years of OO experience in PHP but haven't really touched Java since Uni. So please let me know if these a Java'isms (things that are common in Java land, even if they are perhaps not best OO approaches). I am working my way through this guide to learn Vertx and refresh my very old Java experience.

In step 3 - Database service interface, the example makes use of the fluent design pattern in an example block where it would be completely illogical to use one. I would suggest removing it in order to keep the complexity as low as possible and focus on a practical example.

PR Here:- https://github.com/vert-x3/vertx-guide-for-java-devs/pull/50

**Comment by gargoyle** [comment]
Is that it? A link to Fowler and then closed?

**Comment by jponge** [comment]
Fluent APIs are widespread and not just in Java. Ruby, JS,... many
languages actually. I don't see why they should be a problem.

**Comment by gargoyle** [comment]
I don't dispute that - indeed they are very useful when used appropriately. My argument here is that the pattern does not fit the use case in this specific example.
