### ISSUE TITLE
step 5: changes to index template not mentioned

### ISSUE THREAD

**Issue by andrew-g-za** [vert-x3/vertx-guide-for-java-devs#62]
Step 5 adds a new feature activated by a backup button, but the tutorial doesnt provide instructions for updating the template with the necessary changes.

p.s. i'm happy to open a pull request with a fix

**Comment by jponge** [comment]
@andrew-g-za yes please ;-)

**Comment by andrew-g-za** [comment]
@jponge happy to help - i've opened a PR for you.

**Comment by jponge** [comment]
Thanks @andrew-g-za
