### ISSUE TITLE
Step 3: Wrong package name when deploying HttpServerVerticle

### ISSUE THREAD

**Issue by rsippl** [vert-x3/vertx-guide-for-java-devs#71]
This line
https://github.com/vert-x3/vertx-guide-for-java-devs/blob/380eb67bd6462be8f91cd7dc5dd85628e582a55b/step-3/src/main/java/io/vertx/guides/wiki/MainVerticle.java#L40

should read

`"io.vertx.guides.wiki.http.HttpServerVerticle",`

**Comment by jponge** [comment]
Thanks for spotting this, can you please make a pull-request?
