### ISSUE TITLE
step-7 ApiTest failed with null pointer exception

### ISSUE THREAD

**Issue by tanvp112** [vert-x3/vertx-guide-for-java-devs#79]
Hi,

Not sure if this is a known bug; when step-7 is built and test with 4.0.0-milestone4, ApiTest.play_with_api will failed at JWK.java line 318 because secret is null.

![image](https://user-images.githubusercontent.com/57385114/74591652-a68db080-5054-11ea-9b67-e7770da22ffd.png)

The test passed when built using 3.8.5 (noticed JWTAuthProviderImpl has changed quite a bit in 4.0)

**Comment by tanvp112** [comment]
Added secret key to jwt provider resolved the issue. Perhaps 4.0 breaking change could mention secret key handling is not the same as 3.8.x.

**Comment by jponge** [comment]
We are going to need a rewrite of the guide for Vert.x 4.
