### ISSUE TITLE
Chap 2/step-1 vertx-default-jul-logging.properties

### ISSUE THREAD

**Issue by burrsutter** [vert-x3/vertx-guide-for-java-devs#8]
The concept of logging is introduced (awesome!) but not how to configure the 
vertx-default-jul-logging.properties 
where I want my "business logic" logs (LOGGER.debug, to be visible) but not necessarily all the vert.x internals, hazelcast, etc.

**Comment by jponge** [comment]
Logging over JUL is quite cumbersome and inconsistent.

I'm migrating the logging to slf4j + logback, much saner choices.
