### ISSUE TITLE
Step-2: WikiDatabaseVerticle.onMessage must call return after message.fail

### ISSUE THREAD

**Issue by muehlehh** [vert-x3/vertx-guide-for-java-devs#9]
In the onMessage method: If we could not find an entry for action in
the header we should fail the message and stop processing by calling
return right after failing the message. If we do not call return the
switch will throw a NPE.

if (!message.headers().contains("action")) {
      message.fail(ErrorCodes.NO_ACTION_SPECIFIED.ordinal(), "No action header specified");
      return;   // <-- this should be added
}
String action = message.headers().get("action");
switch (action) {

Regards,
Jens

**Comment by jponge** [comment]
Thanks!
