### ISSUE TITLE
Configure Maven Shade Plugin with ServicesResourceTransformer

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-guide-for-java-devs#91]
The Maven Shade Plugin is configured with `AppendingTransformer`.

A simpler solution is to use the `ServicesResourceTransformer` which does not require a list of service files (the Gradle Shadow Plugin does this by default.)

In practice, the examples in the guide work fine with `AppendingTransformer`. But for a lot of users the guide serves as a starting point so it would be better to provide a more robust config.

**Comment by jponge** [comment]
Thank you @tsegismont
